### ISSUE TITLE
Configuration suggestion - manage with profiles, not per wifi.

### ISSUE THREAD

**Issue by james-darkfox** [abarisain/dmix#374]
Some people have multiple MPD servers in different locations, they may even have to connect through a tunnel. This would be better managed through profiles, maybe auto detect which we can connect to and to not leak any information - let that profile have the wifi AP-name in it's settings. (Profile, not tied to the AP, but rather the AP is just a variable to configure within the profile)

My preposal is for the menu to have the profiles listed so you can change which you're talking to. Hold and reconfigure that profile.

Without these profiles, it becomes annoying to change the host ip while on the same WiFi AP just to talk to another computer. Personally, I use MPD to control my volume on my computers and maybe one day, TV. :P

Loving this app, a friend said it looks too plain but I love this minimalistic feel. Maybe let the user set the colours for different things? Be even better if those colourschemes were per-profile settable. I.e. Blue for home, Green for work and Red for tunnel to home from work. :P

**Comment by gjanssens** [comment]
I'm looking forward to seeing this profile based configuration appear in a released version of MPDroid. I have multiple mpd servers running at home and it's pretty cumbersome to manage all of them with the current wifi based configuration method.

**Comment by brokensbone** [comment]
Seriously keen on this.

The last comment from abarisain in here is that this would be put on the back-burner for a while, due to being a less common request. Has it been dropped altogether or is it still in the pipeline?

If anyone else is keen on it, make yourselves known here! I'm sure there must be others who want this. I know Sound@Home has been built for Volumio specifically to cater to this, but the actual player controls in that aren't nearly as polished as MPDroid. Thanks for all the hard work.

**Comment by technoplunk** [comment]
I am seriously waiting for this feature. I currently have 2 Raspberry Pi based mpd players in my house. Currently I use one copy of MPDroid on my phone and a separate one on my tablet to manage them. Of course now I'm looking at adding a third mpd server in the basement so I would really like a single android app that can handle multiple servers.

**Comment by avuton** [comment]
Talk is cheap, guys. Code it up, send a pull request, if it's acceptable it'll become part of this tree. We need no more "me too" s. We want it too.

**Comment by hurzl** [comment]
What do you mean by "manage with profiles"? Just a list of servers like in @abarisain's mockup wouldn't be enough?

**Comment by jalonsomartinez** [comment]
I already switched to MPD remote (paid) due to the lack of this feature.

**Comment by abarisain** [comment]
I don't get paid to do MPDroid, and I never made you spend a dime for it. If you found another client that fits your need better, enjoy it :)  I'm not Microsoft or Google, I'm not fighting for a market.

MPDroid is a hobby to me, it doesn't bring any food to the table (I did enjoy some beers thanks to donators, which I really appreciate but have never asked anything in return).  


Closing this. I *really* want to do multi server capability in MPDroid, but only those who have collaborated even a single line know how complex MPDroid is, and how much time it would take to do that. We've always wanted to make single server experience amazing before forking off to multi server, and I believe we've made great progress, thanks to @avuton.  Since we don't have much use for multiserver ourselves, it's not a priority.  

I'm closing this, since I think the dicussion has run its course. I'll comment on pull requests or emails (I know we have pretty high requirements for pull requests), and some people already volounteered to work on that (which is hard because of @avuton 's HUGE overhaul of the connection code, which will make the whole thing less frustrating).

**Comment by james-darkfox** [comment]
Just thought I'd add this as a quick hack for anyone who needs multiple servers...

1. Settings
2. Users
3. New user
4. Give the new user MPDroid
5. Lock the android device and go to the new user
6. Configure and enjoy MPDroid for the other server
