### ISSUE TITLE
Sort albums by year, performance issue

### ISSUE THREAD

**Issue by tkone** [abarisain/dmix#388]
Hello,
I've got a few artists with more than a hundred albums in my library, mostly kid's stuff.
If the settings option to sort by year is NOT activated, it takes only one second to show all of the artist's albums when the artist has been selected.
If the option is activated, it merely takes forever for the albums to be shown.
Exactly, for 107 albums it took 1:50 minutes to load the album view.
Cover art had not even been activated.
Regards
Thorsten

**Comment by a-mair** [comment]
Hi,

sorry for digging out this issue, but I think my issue is related.

While trying to find out why MPDroid is so slow when retrieving an artist's albums I think I found a (possible) improvement:
In MPD.java there's the getFirstTrack() method which issues _three_ queries for each album. At least that's the case with MPD v0.19.9 (latest Gentoo stable) and they way my MP3 files are tagged.

For example:
client: [12] process command "find "albumartist" "Aerosmith" "album" "Pump" "track" "1""
client: [12] command returned 0
client: [12] process command "find "albumartist" "Aerosmith" "album" "Pump" "track" "01""
client: [12] command returned 0
client: [12] process command "search "albumartist" "Aerosmith" "album" "Pump" "track" "1""
client: [12] command returned 0

The problem is that MPD saves the track number as "01/10" in its database (because Picard tagger put that in the MP3 tags) and uses a string compare so only "01/10" would match.
The final "search" for track "1" would return multiple songs if the album contains ten or more tracks.
Finding the first track of an album will also fail, if someone doesn't collect full albums but only the favourite tracks.

Maybe the "window" argument as described at http://www.musicpd.org/doc/protocol/database.html#command_find would be better?

Best regards,
Andreas

**Comment by hurzl** [comment]
Can you give an example of a "window" find command?  Is this since 0.19?

**Comment by a-mair** [comment]
It's a pity that the documentation at http://www.musicpd.org/doc/protocol/database.html#command_find doesn't note that it's not included until MPD 0.19.10. I've used MPD GIT.

Example for the first track in an album (not necessary track number "1"):
find "albumartist" "Aerosmith" "album" "Pump" window 0
