### ISSUE TITLE
Lyrics support

### ISSUE THREAD

**Issue by AlexParamonov** [abarisain/dmix#574]
Integration with musiXmatch player would be the best

**Comment by martignlo** [comment]
It looks like it is possible to integrate with musiXmatch using broadcast intents: https://developer.musixmatch.com/documentation/floating-lyrics.

This method does not seem to require to accept any term and it doesn't seem dangerous (since mpdroid won't need to access any lyric but just broadcast what's being currently played).

**Comment by abarisain** [comment]
Hi and thanks for your feedback.  

MusiXmatch could use the remote control APIs... Anyway, I'm not really against that since they are """standard""" broadcasts. One advantage of doing that would also be helping Lastfm scrobblers recognize mpdroid.

**Comment by avuton** [comment]
This has already been fixed by #20, I mean, sure additional functionality, blah blah, but seriously, there is enough stuff to do without adding more support for something already support.

**Comment by abarisain** [comment]
It is with great shame that I'm admitting that I never saw that commit :D

**Comment by avuton** [comment]
Probably a lesser known feature :+1:

**Comment by n03l** [comment]
It would be nice if QuickLyric used the same exact approach (the intent seems to be a standard one) so that a single method would work with multiple lyrics apps.

Anyway, I understand, that this is definitely a very low priority request. I just wanted to point out that there exist a very simple way to integrate with MusiXmatch.
