### ISSUE TITLE
Add support for service (mpd) discovery using avahi/dns-sd?

### ISSUE THREAD

**Issue by loblik** [abarisain/dmix#742]
This is probably not a big issue for most users. But if you run mpd on laptop it probably change its address as you switch wifi networks. And often you can't use hostname since these cheap home routers usually don't resolve local names.

However according to this
http://developer.android.com/training/connect-devices-wirelessly/nsd.html#discover
it seems it shouldn't be that hard to implement discovery using dns-sd as zeroconf is already implemented in mpd.

**Comment by abarisain** [comment]
Hi!

I'll close this, because we already have issues about that one, but let me explain why we don't have it:

It's a pretty requested feature (heck, one I'd want myself), and there have already been some test implementations with JmDNS (this was before the 4.x days when the Android API was available), which kinda worked.  
The thing is that I wanted to implement this with real multi server support, and not before (since it would have need to be redone). Sadly, I never got around working on that, and my developement on MPDroid has pretty much stopped as I moved to other projects. These days, I mostly do the UI improvements, and maintain the play store builds (whenever I can).

That said, people wanted MPDroid to use discovery to find the hostname or ip and save it, while you want MPDroid to always get the ip from avahi. I think this can work but could easily get flaky (takes some time to warm up, etc...). Not a bad idea though!
