### ISSUE TITLE
Simple multi-server solution

### ISSUE THREAD

**Issue by marki555** [abarisain/dmix#745]
From reading old issues it seems that having multi-server support means rewritting a lot of code...
What about a workaround? Instead of having multi-server support, install 2 or 3 versions of mpdroid and configure each with different server. For this, we would need to have packaged mpdroid under few different names (mpdroid, mpdroid-2, mpdroid-3 for example) to be able to install it multiple times to the same device.

Then at least print the server name somewhere in the UI, so that we know which instance is currently active. Plus having differently colored icon in app drawer and in widget for each instance would be perfect.

**Comment by avuton** [comment]
That's very hacky, and while it might work, I don't think anyone is going to actually code it. The connection code is pretty good now, someone just needs to code the multi-server stuff (read: not me). And if you've looked at the commits, not many people otherwise are maintaining MPDroid at the moment.
