### ISSUE TITLE
Pause/Play disables stream

### ISSUE THREAD

**Issue by BlitzKraft** [abarisain/dmix#780]
When I pause, after a few minutes the stream resets. That is, the stream checkmark disappears. When I hit play, it plays - but without streaming. The server starts playing as expected. 

The stream setting is also not persistent. If I restart the application, by default it starts without streaming.

**Comment by hurzl** [comment]
Yes probably on streams the pause button should behave like a stop button. I enabled the stop button just for streams.

**Comment by BlitzKraft** [comment]
How can I enable it? Is there a current build with the stop enabled?

**Comment by abarisain** [comment]
Depending on your version of mpd, it's not the same. Pausing may keep a stream running with no noise.

**Comment by hurzl** [comment]
> Depending on your version of mpd, it's not the same. Pausing may keep a stream running with no noise.

But what's the use of this?

**Comment by BlitzKraft** [comment]
I don't mind if the pause behaves like a mute button. But when I hit play, the streaming option gets cancelled and I have to re-enable it. 

My MPDroid version is 1.07.2 Final ba27d2a-c (54)

**Comment by hurzl** [comment]
> How can I enable it? Is there a current build with the stop enabled?

There's a setting

**Comment by abarisain** [comment]
>But what's the use of this? You can always pull down the volume ...

Doesn't disconnect the other clients. You can have something just running mplayer somewhere (or mpdroid with streaming on ;) ) and it will be quiet, and will start again when you resume playing.  
Pulling down the volume doesn't pause the current song.

Anyway, not something I control :)

**Comment by BlitzKraft** [comment]
Enabling the stop remedies this problem.

**Comment by hurzl** [comment]
Ok maybe there may be streams that wait forever to be continued ...

**Comment by avuton** [comment]
Ten people on this planet want persistent streaming and it would take days, or likely weeks, of programming to get right; even then it probably could never be done right due to the necessary MediaPlayer workarounds. There is also a <A HREF="https://github.com/abarisain/dmix/wiki/How-the-service-works-in-MPDroid#How_streaming_works">wiki</A> article detailing how streaming should work. It's not perfect, but it should give an idea of the expectation. This has been discussed previously in closed bugs. Also, stop can be disabled in the options.
