### ISSUE TITLE
Coverart url query string too smart

### ISSUE THREAD

**Issue by wvengen** [abarisain/dmix#830]
[Volumio](https://volumio.org/) has cover art served at music path `http://volumio.local/albumart?path=` - note the query string, the file path is expected to be appended. Now MPDroid appends the file path to `/albumart` instead of the url parameter (as seen in tcpdump).

Would it make sense to be a little less smart? How could this cover art url be handled?

**Comment by abarisain** [comment]
Well, I'd argue that MPDroid tries to be smart, by appending the path where it should be and preserving the get arguments rather than blindly appending to a string ;)  

I'm afraid that your only way around this is a patch

**Comment by wvengen** [comment]
Thanks for your quick response! Do you have an idea for what the patch would do?

**Comment by hurzl** [comment]
> appending the path where it should be and preserving the get arguments

why is that smarter, or what's the scenario for that?

**Comment by abarisain** [comment]
It's just "smart" url parsing: the path is appended as url compnents, as opposed to the "dumb" way which would be simply appending as a string.  the wanted behavior is debatable but I think both have their use cases

It's that way because there are a lot of cases that need to be handled correctly (such as escaping)  this uses the URL class.

If you want to fix this, you'll have to tweak the cover provider to set the path as a get parameter rather than appending.

**Comment by wvengen** [comment]
It appears that using (undocumented) path `/cover-art/` also works, so the immediate need is gone.
I'll close this, until someone else has a practical problem. (And the issue remains as documentation.)
